plugins {  
    id 'java-library'  
    id 'net.neoforged.moddev' version '2.0.115'  
}  
  
group = 'deliciousbread481'  
version = '1.0.0'  
  
java {  
    toolchain {  
        languageVersion = JavaLanguageVersion.of(21)  
    }  
}  
  
neoForge {  
    neoFormVersion = "20240808.144430"  
      
    runs {  
        client {  
            client()  
        }  
        server {  
            server()  
        }  
    }  
  
    mods {  
        registrymonitor {  
            sourceSet sourceSets.main  
        }  
    }  
}  
  
dependencies {  
    implementation("net.neoforged:neoforge:21.1.228")  
}  
  
tasks.withType(JavaCompile).configureEach {  
    options.encoding = 'UTF-8'  
}