plugins {  
    id 'java-library'  
}  
  
group = 'deliciousbread481'  
version = '1.0.0'  
  
java {  
    toolchain {  
        languageVersion = JavaLanguageVersion.of(java_version)  
    }  
}  
  
neoForge {  
    neoFormVersion = "${neoform_version}"  
    accessTransformers {  
        from('src/main/resources/META-INF/accesstransformer.cfg')  
    }  
  
    runs {  
        client {  
            client()  
        }  
        server {  
            server()  
        }  
    }  
  
    mods {  
        registrymonitor {  
            sourceSet sourceSets.main  
        }  
    }  
}  
  
dependencies {  
    implementation("net.neoforged:neoforge:${neoforge_version}")  
}  
  
tasks.withType(JavaCompile).configureEach {  
    options.encoding = 'UTF-8'  
}