modLoader="javafml"  
loaderVersion="[3,)"  
license="LGPL v2.1"  
  
[[mods]]  
    modId="registrymonitor"  
    version="1.0.1"  
    displayName="Registry Monitor"  
    authors="DeliciousBread481"  
    description='''  
    Monitors registry registrations and logs call stacks for specific registries.  
    '''  
  
[[mixins]]  
    config = "registrymonitor.mixins.json"